version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ec2-user