version: '3'

services:
  db:
    container_name: myH2
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "8081:81"
    environment:
      H2_OPTIONS: "-ifNotExists"
    volumes:
      - ./h2:/opt/h2-data
    restart: always

  app:
    container_name: test_app
    build: .
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://myH2:1521/Fit4You
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db