spring:
  profiles:
    default: local

  config:
    import:
      - optional:classpath:/secret-config.yml #실제 배포환경에서 사용할 키
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
ai:
  server:
    url: localhost
springdoc:
#  packages-to-scan: com.test.demo
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /api           # Swagger UI 경로 => localhost:8000/{path}
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

app-config: #테스트용 키
  jwt-key: "9esMvnzaD0/Ph+0u9j6WdO+vLCbkI52g8kP09eksodQ="

#server:
#  address: 0.0.0.0 # 또는 자신의 IPv4 주소
#  port: 8080