spring:
  config:
    activate:
      on-profile: docker
  h2:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:1521/Fit4You
    username: sa
    password:

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
