-- INSERT INTO disease (name,related_part) VALUES ('거북목','목');
-- INSERT INTO disease (name,related_part) VALUES ('질병2','어깨');
-- INSERT INTO disease (name,related_part) VALUES ('손목터널증후군','손목');
-- INSERT INTO disease (name,related_part) VALUES ('허리디스크','허리');
-- INSERT INTO disease (name,related_part) VALUES ('골프엘보','팔꿈치');
-- INSERT INTO disease (name,related_part) VALUES ('질병6','무릎');
--
-- INSERT INTO exercise (name,disease_id,video_link) VALUES ('버드독',1,'버드독_기준');
-- INSERT INTO exercise (name,disease_id,video_link) VALUES ('허리운동',2,'허리_기준');
-- INSERT INTO exercise (name,disease_id) VALUES ('운동3',3);
-- INSERT INTO exercise (name,disease_id) VALUES ('운동4',4);
-- INSERT INTO exercise (name,disease_id) VALUES ('운동5',5);
--
--
