### 추천 운동목록 생성 요청

GET http://localhost:8080/trainings/recommend
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg0OTk5NjQ1LCJleHAiOjE2ODUwMDMyNDV9.DQGlQy5iRk-E_fyNUF7YoPvXbzrFhInczlPZqZXEhIo

{
  "email": "test@email.com"
}

