### 추천 운동목록 생성 요청

GET http://localhost:8080/trainings/recommend
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1MDM3NTU1LCJleHAiOjE2ODUwNDExNTV9.2HROY-YrugNfiqWtrRToMOgPaUGFkTcaqAsGclFWKmY

{
  "email": "test@email.com"
}

